services:
  jenkins:
    image: docker.io/jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home


  agent:
    image: docker.io/jenkins/ssh-agent:latest
    container_name: agent
    expose:
      - "22"
    volumes:
      - ./onedrive_data:/home/jenkins/agent/onedrive_data
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}


  onedrive:
    image: docker.io/driveone/onedrive:edge
    userns_mode: keep-id
    restart: always
    volumes:
      - ./onedrive_conf:/onedrive/conf
      - ./onedrive_data:/onedrive/data
    environment:
      - ONEDRIVE_DOWNLOADONLY=1
      - ONEDRIVE_CLEANUPLOCAL=1
    labels:
      io.containers.autoupdate: "image"
