services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      onedrive:
        condition: service_healthy
    volumes:
      - ./service/onedrive/data:/app/data
      - ./output:/app/output
    secrets:
      - VAULT_ADDR
      - VAULT_CACERT
      - VAULT_ROLE_ID
      - VAULT_SECRET_ID
      - vault.crt
    healthcheck:
      test: bash -c 'exec 3<>/dev/tcp/localhost/22'
      interval: 30s
      timeout: 5s
      retries: 3

  onedrive:
    image: docker.io/driveone/onedrive:edge
    container_name: onedrive_justicier
    userns_mode: keep-id
    entrypoint: ["/entrypoint-wrapper.sh"]
    volumes:
      - ./service/onedrive/conf:/onedrive/conf
      - ./service/onedrive/data:/onedrive/data
      - ./service/onedrive/logs:/onedrive/logs
      - ./service/onedrive/entrypoint-wrapper.sh:/entrypoint-wrapper.sh:ro
    secrets:
      - DRIVE_ID
    networks:
      - jenkins_net
    healthcheck:
      test: sh -c '[ -s /onedrive/conf/items.sqlite3-wal ]'
      interval: 60s
      timeout: 5s
      retries: 2

secrets:
  VAULT_ADDR:
    file: ./secrets/VAULT_ADDR
  VAULT_CACERT:
    file: ./secrets/VAULT_CACERT
  VAULT_ROLE_ID:
    file: ./secrets/VAULT_ROLE_ID
  VAULT_SECRET_ID:
    file: ./secrets/VAULT_SECRET_ID
  vault.crt:
    file: ./secrets/vault.crt
  DRIVE_ID:  # Needs file integration with HashiCorp Vault
    file: ./secrets/DRIVE_ID

networks:
  jenkins_net:
    external: true
