services:
  jenkins:
    container_name: jenkins
    image: docker.io/jenkins/jenkins:lts
    user: "1002:1002"
    expose:
      - ${JENKINS_PORT_INTERNAL}
    volumes:
      - ./service/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--httpPort=${JENKINS_PORT_INTERNAL}"
    restart: always
    networks:
      - justicier_net
    healthcheck:
      test: curl -fsSL http://localhost:${JENKINS_PORT_INTERNAL}/login || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


  agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: agent
    expose:
      - ${AGENT_PORT_INTERNAL}
    volumes:
      - ./service/onedrive_data:/home/jenkins/agent/onedrive_data
      - type: bind
        source: ./service/jenkins_agent_keys
        target: /home/jenkins/.ssh
        read_only: false
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    secrets:
      - CLIENT_ID
      - CLIENT_SECRET
      - SHAREPOINT_DOMAIN
      - SHAREPOINT_FOLDER_INPUT
      - SHAREPOINT_FOLDER_OUTPUT
      - SHAREPOINT_LIST_GUID
      - SHAREPOINT_LIST_NAME
      - SITE_NAME
      - TENANT_ID
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SERVER
      - SMTP_PORT
    restart: always
    networks:
      - justicier_net
    healthcheck:
      test: bash -c 'exec 3<>/dev/tcp/localhost/22'
      interval: 30s
      timeout: 5s
      retries: 3

  onedrive:
    image: docker.io/driveone/onedrive:edge
    container_name: onedrive
    userns_mode: keep-id
    volumes:
      - ./service/onedrive_conf:/onedrive/conf
      - ./service/onedrive_data:/onedrive/data
      - ./service/onedrive_logs:/onedrive/logs
    labels:
      io.containers.autoupdate: "image"
    restart: unless-stopped
    networks:
      - justicier_net
    healthcheck:
      test: sh -c '[ -s /onedrive/conf/items.sqlite3-wal ]'
      interval: 60s
      timeout: 5s
      retries: 2
    #entrypoint: /bin/sh
    #command: -c "tail -f /dev/null"
    #stdin_open: true
    #tty: true
    #entrypoint: "onedrive --monitor"



  nginx:
    image: nginx:stable
    container_name: nginx-firewall
    ports:
      - "0.0.0.0:${FIREWALL_PORT_EXTERNAL}:${FIREWALL_PORT_INTERNAL}"
    volumes:
      - ./service/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service/nginx_conf/proxy_params:/etc/nginx/proxy_params:ro
      - ./service/nginx_logs:/var/log/nginx
    depends_on:
      jenkins:
        condition: service_healthy
      agent:
        condition: service_healthy
      onedrive:
        condition: service_healthy
    restart: always
    networks:
      - justicier_net
    healthcheck:
      test: curl -fsSL http://localhost:80/healthz || exit 1
      interval: 30s
      timeout: 5s
      retries: 3


secrets:
  CLIENT_ID:
    file: ./secrets/CLIENT_ID
  CLIENT_SECRET:
    file: ./secrets/CLIENT_SECRET
  SHAREPOINT_DOMAIN:
    file: ./secrets/SHAREPOINT_DOMAIN
  SHAREPOINT_FOLDER_INPUT:
    file: ./secrets/SHAREPOINT_FOLDER_INPUT
  SHAREPOINT_FOLDER_OUTPUT:
    file: ./secrets/SHAREPOINT_FOLDER_OUTPUT
  SHAREPOINT_LIST_GUID:
    file: ./secrets/SHAREPOINT_LIST_GUID
  SHAREPOINT_LIST_NAME:
    file: ./secrets/SHAREPOINT_LIST_NAME
  SITE_NAME:
    file: ./secrets/SITE_NAME
  TENANT_ID:
    file: ./secrets/TENANT_ID
  SMTP_USERNAME:
    file: ./secrets/SMTP_USERNAME
  SMTP_PASSWORD:
    file: ./secrets/SMTP_PASSWORD
  SMTP_SERVER:
    file: ./secrets/SMTP_SERVER
  SMTP_PORT:
    file: ./secrets/SMTP_PORT

networks:
  justicier_net:
    driver: bridge
